# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.provider "parallels" do |p, o|
      p.memory = "512"
    end
    # Increase memory for Virtualbox
    config.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
    end
    # Increase memory for VMware
    ["vmware_fusion", "vmware_workstation"].each do |p|
      config.vm.provider p do |v|
        v.vmx["memsize"] = "512"
        v.vmx["numvcpus"] = "2"
      end
    end
  #  config.vm.provision "shell", path: "bootstrap.sh"

  ServerCount = 9
  # Demostack Server Nodes
  (1..ServerCount).each do |i|
    config.vm.define "nserver#{i}" do |servernode|
      servernode.vm.box = "bento/ubuntu-20.04"
      servernode.vm.hostname = "nserver#{i}.node.consul"
      servernode.vm.network "public_network", use_dhcp_assigned_default_route: true
      servernode.vm.network "private_network", ip: "172.17.16.10#{i}"
      servernode.vm.provision "shell", path: "scripts/bootstrap.sh", preserve_order: true
     
    end
  end


  end
