Vagrant.configure("2") do |config|
  config.vm.provider "parallels" do |p, o|
    p.memory = "4096"
  end

  # Increase memory for Virtualbox
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
  end

   # Increase memory for VMware
  ["vmware_fusion", "vmware_workstation"].each do |p|
    config.vm.provider p do |v|
      v.vmx["memsize"] = "4096"
    end
  end
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/kikitux/curl-bash/master/provision/go.sh"
end
